<a href="https://colab.research.google.com/github/sheikhhammaad/programming-20-20/blob/master/_RegressionStudentMaterial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression Study Material

# Simple Linear Regression With scikit-learn

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression

There are five basic steps when you’re implementing linear regression:

    Import the packages and classes you need.

    Provide data to work with and eventually do appropriate transformations.

    Create a regression model and fit it with existing data.

    Check the results of model fitting to know whether the model is satisfactory.

    Apply the model for predictions.

Step 1: Import packages and classes

Step 2: Provide data

In [ ]:
X = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

Step 3: Create a model and fit it

In [ ]:
model = LinearRegression()

In [ ]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model = LinearRegression().fit(X, y)

# Step 4: Get results

In [ ]:
R_sq = model.score(X, y)
print('coefficient of determination:', R_sq)

coefficient of determination: 0.7158756137479542


In [ ]:
print('intercept:', model.intercept_)

print('slope:', model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [ ]:
new_model = LinearRegression().fit(X, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)

print('slope:', new_model.coef_)

intercept: [5.63333333]
slope: [[0.54]]


# Step 5: Predict response

In [ ]:
y_pred = model.predict(X)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [ ]:
y_pred = model.intercept_ + model.coef_ * X
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [ ]:
X_new = [[5], [30]]

In [ ]:
y_new = model.predict(X_new)
print(y_new)

[ 8.33333333 21.83333333]


In [ ]:
X_new = np.arange(5).reshape((-1, 1))
print(X_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
y_new = model.predict(X_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
